### ISSUE TITLE
PDE definition cannot handle simple multiplication by a constant?

### ISSUE THREAD

**Issue by SimonEnsemble** [SciML/MethodOfLines.jl#1]
this gives an error, with `D₀::Float64`.
```
	diff_eq = ∂t(c(x, t)) ~ D₀ * ∂x(
		 ∂x(c(x, t)) / (1.0 + exp(α * (c(x, t) - χ)))
		)
```

my hack to get it to work:
```
	diff_eq = ∂t(c(x, t)) ~ ∂x(
		 ∂x(c(x, t)) / (1.0/D₀ + exp(α * (c(x, t) - χ))/D₀)
		)
```

the error is:
```
MethodError: no method matching collect_ivs_from_nested_differential!(::Set{Any}, ::SymbolicUtils.Div{Real, SymbolicUtils.Term{Real, Nothing}, SymbolicUtils.Add{Real, Float64, Dict{Any, Number}, Nothing}, Nothing})

Closest candidates are:

collect_ivs_from_nested_differential!(::Any, !Matched::SymbolicUtils.Term)
```

**Comment by SimonEnsemble** [comment]
the key was to add `expand_derivatives()`.
```julia
diff_eq = expand_derivatives(∂t(c(x, t)) ~ ∂x(D * ∂x(c(x, t))))
```
makes the error disappear. found this in:
https://github.com/SciML/ModelingToolkit.jl/issues/1197

**Comment by xtalax** [comment]
This is due to limitations in `@rule`, in particular the lack of equivalance between `*(x^-1, u(t, x), a` and `/(*(a, u(t, x), x)` in the matching. a future PR will fix this, but this gets complicated very quickly as you have to match each possible set of nested functions individually

**Comment by xtalax** [comment]
@shashi What should I do about this?
