### ISSUE TITLE
Using remake to bypass re-discretizing over parameters causing an error

### ISSUE THREAD

**Issue by thompsonmj** [SciML/MethodOfLines.jl#105]
As a prerequisite to #104, the [Remake with different parameter values](http://methodoflines.sciml.ai/dev/tutorials/params/#Remake-with-different-parameter-values) example gives the following error on the `solve` step:

`ERROR: MethodError: no method matching *(::Pair{Num, Float64}, ::Float64)`

**Comment by xtalax** [comment]
Sorry, this is a known issue with that tutorial - please see [here](https://github.com/xtalax/MethodOfLines.jl/blob/upwindfix/docs/src/tutorials/params.md) for the updated version.

**Comment by ChrisRackauckas** [comment]
Can we turn this into a more informative error message?

**Comment by thompsonmj** [comment]
> Sorry, this is a known issue with that tutorial - please see [here](https://github.com/xtalax/MethodOfLines.jl/blob/upwindfix/docs/src/tutorials/params.md) for the updated version.

Thanks, that syntax works.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/SciMLBase.jl/tree/master/src/ensemble

**Comment by thompsonmj** [comment]
Shoot ... actually running with `remake()` doesn't correctly update new parameters in that example. It just uses the original parameters from the equation definition.

**Comment by MilkshakeForReal** [comment]
> Shoot ... actually running with `remake()` doesn't correctly update new parameters in that example. It just uses the original parameters from the equation definition.

It's fixed later. Check again.

**Comment by thompsonmj** [comment]
Updated and working. Thanks @MilkshakeForReal!

**Comment by MilkshakeForReal** [comment]
So you can close this issue now i guess
