### ISSUE TITLE
confusing locations of spatial points with periodic conditions

### ISSUE THREAD

**Issue by MilkshakeForReal** [SciML/MethodOfLines.jl#109]
The derived ODE problem below contains 5 spatial points, from the first inner point to the right boundary. I believe it's a natural result of structural simplification. But the users need to be notified the points are located from the first inner point to the right boundary, not the other way around

```julia
using ModelingToolkit, MethodOfLines, DomainSets
using OrdinaryDiffEq

@parameters t x
@variables u(..) 

Dt = Differential(t)
Dx = Differential(x)

eq = Dt(u(t, x)) ~  -2.0  * Dx(u(t, x))

tmin,tmax = 0, 4
xmin,xmax = 0, 1

domains = [x ∈ Interval(xmin, xmax),
           t ∈ Interval(tmin, tmax)]

bcs = [u(0,x) ~ sin(2π*x),
       u(t,xmin)~u(t,xmax)]
       
@named pdesys = PDESystem(eq,bcs,domains,[t,x],[u(t,x)])

discretization = MOLFiniteDifference([x=>0.2], t, approx_order=2, grid_align=center_align)
prob = discretize(pdesys,discretization)

@show prob.u0

grid = get_discrete(pdesys,discretization)
grid[u(t,x)]
```

**Comment by xtalax** [comment]
Please retrieve the solution like this:
`solu = [map(d -> sol[d][i], grid[u(t, x)]) for i in 1:length(sol[t])]`

There are no guarantees on the shape of the raw solution after `structural_simplify`

**Comment by MilkshakeForReal** [comment]
> Please retrieve the solution like this: `solu = [map(d -> sol[d][i], grid[u(t, x)]) for i in 1:length(sol[t])]`
> 
> There are no guarantees on the shape of the raw solution after `structural_simplify`

This is a bit cumbersome. I am satisfied with `sol[grid[u(t,x)]]`. Guess we just have to save the ODE prob and the grid too. Thanks!

**Comment by xtalax** [comment]
This is true until we have the solution interface, which will handle this automatically. That indexing may be better, I will see if I can update the docs to use that.
