### ISSUE TITLE
Proposed interface allowing user choice of advection scheme

### ISSUE THREAD

**Issue by xtalax** [SciML/MethodOfLines.jl#133]
```julia
    MOLFiniteDifference(dxs, time=nothing;
                        approx_order = 2, advection_scheme = UpwindScheme(),
                        grid_align = CenterAlignedGrid(), kwargs...)
```

`advection_scheme`: The scheme to be used to discretize advection terms, i.e. first order spatial derivatives and associated coefficients. Defaults to `UpwindScheme()`. This is the only relevant scheme at present. A coming PR will add `WENOScheme()`.

Is this a good interface? Should this default to WENO in future?
@ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
Yeah I think a WENO default could be good.
