### ISSUE TITLE
Move to extrapolation based boundary proximity handling

### ISSUE THREAD

**Issue by xtalax** [SciML/MethodOfLines.jl#136]
Currently we use a stencil centrepoint shifting method to deal with domain edges, I propose moving to an extrapolation based approach to ensure stability, adding extra ghostpoints to pad the domain

**Comment by xtalax** [comment]
@ChrisRackauckas @ranocha thoughts?

**Comment by ChrisRackauckas** [comment]
Is the extrapolation stable? I don't remember it being so.

**Comment by xtalax** [comment]
I haven't performed stability analysis on the stencil given in the WENO text, Having thought about this I think I will use a high order interpolation that also references the boundary states, though am suspicious that this is equivalent to just shifting the centrepoint. Perhaps a multidimensional interpolation could work?

**Comment by ranocha** [comment]
The only provably stable WENO methods I know of are the ones of Carpenter et al.

- https://doi.org/10.1016/j.jcp.2011.01.043
- https://doi.org/10.1007/978-1-4614-5389-5_6

You won't like that you need to know something about the equations you are discretizing - so it doesn't fit the general framework here. Having said that, I think Clawpack provides some extrapolation BCs for their WENO methods (but i can't give you specific references).

**Comment by hhaensel** [comment]
>
