### ISSUE TITLE
Mixed Space and Time Derivatives

### ISSUE THREAD

**Issue by dynamic-queries** [SciML/MethodOfLines.jl#158]
Consider
![image](https://user-images.githubusercontent.com/81833704/190390567-4563aadb-910e-4d1e-9b9e-243f7806522b.png)
Any unspecified symbol is a real constant.

The time domain is not explicitly separable. I guess you could regard the time variable in the mixed derivatives as a stand-in auxiliary space variable... but not sure. @xtalax What do you think ? 

Can we add this feature here in the future?

**Comment by xtalax** [comment]
Auxiliary variables should work here, substituting `u_xx` as an auxiliary variable and taking its time derivative for those mixed derivatives. Second order time is already implemented, but there is currently a [bug](https://github.com/SciML/ModelingToolkit.jl/issues/1741) upstream preventing solution retrieval. When this is fixed I expect you to be able to solve this though! What are your BCS? The pi suggests periodic, which is even better, though there is currently some weirdness with multiple non periodic BCs per boundary, which you'd need for the `u_xxxx` term.
