### ISSUE TITLE
Allow arbitrary approximation order 

### ISSUE THREAD

**Issue by xtalax** [SciML/MethodOfLines.jl#16]
At the moment approximation order is hardcoded to 2, this needs to be generalized to higher orders for the following:

- [x] Cartesian Finite Difference.
- [x] Spherical Finite Difference.
- [x] Nonlinear Cartesian Laplacian.
- [x] Nonlinear Spherical Laplacian.

**Comment by dynamic-queries** [comment]
Am I right in inferring that the discretize method for a spherical domain is open for contribution ? 
If so, I would like to know the discretization scheme(For the azimuthal coordinate) that you had in mind. Any references is really appreciated! :D
