### ISSUE TITLE
Obtain PDE solution

### ISSUE THREAD

**Issue by dvignon** [SciML/MethodOfLines.jl#178]
Running [this](http://methodoflines.sciml.ai/stable/tutorials/params/) code (from the documentation). 
First, it seems that `discrete_x = sol[x]` and `discrete_t = sol[t]` do not work. After replacing with `discrete_x = 0:0.1:1` and `discrete_t = sol.t`, I get the following error message: 

ERROR: ArgumentError: u(t, x) is either an observed nor a state variable.

I think this might be related to #6

**Comment by bowenszhu** [comment]
Could you check your version of MethodOfLines.jl with `]st  -m MethodOfLines`?
You probably need [v0.5.0](https://github.com/SciML/MethodOfLines.jl/releases/tag/v0.5.0) or newer versions to make `sol[x]` and `sol[u(t, x)]` work.
You can update your installation with `]up MethodOfLines` or `import Pkg; Pkg.add("MethodOfLines")`.

**Comment by dvignon** [comment]
Thank you so much. This now works. I ran the update command before posting but did not realize it was still stuck at 0.4.0.
