### ISSUE TITLE
Passing boundary condition which depends on x

### ISSUE THREAD

**Issue by SourabhJadhav2** [SciML/MethodOfLines.jl#179]
How can we pass a dictionary with key as distance in x direction and value is respect to distance while solving PDE. I tried with separate function with input x from PDE and dictionary but getting error as follows: global method should be placed at the top level, etc.
please help with this

**Comment by xtalax** [comment]
Could you please post some code showing what you mean?

**Comment by SourabhJadhav2** [comment]
example:
I am finding variation of  `u` with time and space.
initially value of `u` over space `x` direction is variable, but it will going to change with time.
How to pass this `u` initial vector to PDE solver?

if you have any example code then please share.
