### ISSUE TITLE
Suppress output in discretization

### ISSUE THREAD

**Issue by verflieger** [SciML/MethodOfLines.jl#271]
When I discretize my PDE with the new version of MethodOfLines, I get a massive REPL output (I use interpolation function for the boundary conditions. The reason is the @show in the following line

https://github.com/SciML/MethodOfLines.jl/blob/7f50744b2a285e90ca91336cdc71c3ef471bb456/src/discretization/generate_bc_eqs.jl#L140

**Comment by xtalax** [comment]
Sorry about this!
