### ISSUE TITLE
'update_varmap!' not being used

### ISSUE THREAD

**Issue by oc18456** [SciML/MethodOfLines.jl#293]
In line 207 in pde_system_transformation.jl, the function update_varmap! is used but has not been imported from PDEBase and so an error is caused.

**Comment by xtalax** [comment]
Can you post the error and code to reproduce?

**Comment by oc18456** [comment]
I used the code:

using Plots, MethodOfLines, DomainSets, ModelingToolkit

@variables u(..) f(..)

@parameters t θ λ P

dθ = Differential(θ)
dθθ = Differential(θ)^2
dθθθθ = Differential(θ)^4
dt = Differential(t)
dtt = Differential(t)^2

function δ(θ)
    return 1/1000*sqrt(2π) * exp(-θ^2/(2*1000^2)) 
end

Iθ = Integral(θ in DomainSets.ClosedInterval(-1.0,1.0))

eq = [
    dtt(u(t,θ)) ~ -dθθθθ(u(t,θ)) + λ^2 * dθ(f(t,θ) - u(t,θ) +0.5*dθ(u(t,θ))^2*dθ(u(t,θ)))+λ^2 * (f(t,θ) - u(t,θ) +0.5*dθ(u(t,θ))^2)+P*δ(θ), 0 ~ Iθ(f(t,θ))
]

bcs = [
    u(t,-1.0) ~ 0.0, u(t,1.0) ~ 0.0,  
    dθ(dθ(u(t,-1.0))) ~ 0.0, dθ(dθ(u(t,1.0))) ~ 0.0,
    dθ(f(t,-1.0)) - dθ(u(t,-1.0)) ~ 0.0, dθ(f(t,1.0)) - dθ(u(t,1.0)) ~ 0.0,
    u(0.0,θ) ~ 0.0, dt(u(0.0,θ)) ~ 0.0
    ]

domains = [t ∈ (0.0,50.0),
           θ ∈ (-1.0,1.0)]

@named pde_sys = PDESystem(eq, bcs, domains, [t,θ], [u(t,θ),f(t,θ)])

discretisation = MOLFiniteDifference([θ => 100],t)

prob = MethodOfLines.discretize(pde_sys, discretisation)

and got the error message:

ERROR: UndefVarError: update_varmap! not defined

I manually changed the export line in pde_system_transformation.jl, and also had to manually copy over the function get_ops but this resolved the issue on my machine.

**Comment by giav1n** [comment]
I have the exact same problem with a stationary 1D pde:

using MethodOfLines,DomainSets,NonlinearSolve,ModelingToolkit
@parameters  x 
@variables u(..)
Dxx = Differential(x)^2
Dx = Differential(x)

D=0.1
L=5

eq= -Dx((x-x^3)*u(x))  +D*Dxx(u(x)) ~ 0
bcs = [u(-L) ~ 0,u(-L)~ 0]

domains = [x ∈ Interval(-L, L)]

@named pdesys = PDESystem(eq, bcs, domains, [x], [u(x)])
dx = 0.1
discretization = MOLFiniteDifference(x => dx, approx_order=2)
prob = discretize(pdesys, discretization)

it works fine in 2D spatial dimension
