### ISSUE TITLE
Fix NonlinearProblem tests

### ISSUE THREAD

**Issue by cmhyett** [SciML/MethodOfLines.jl#334]
As part of  PR #285 , tests inside `test/pde_systems/MOL_NonlinearProblem.jl` were marked as broken to avoid an upstream breaking error.

The error thrown complained about too few equations in the 1D Laplace and the heat eq tests. @xtalax states this is an issue of `structural_simplify`

**Comment by xtalax** [comment]
fixed in 0.10.2
