### ISSUE TITLE
Linear and nonlinear solve for steady state tutorials

### ISSUE THREAD

**Issue by bclyons12** [SciML/MethodOfLines.jl#336]
In the tutorials, the [Steady State Heat Equation](https://docs.sciml.ai/MethodOfLines/stable/tutorials/heatss/#Steady-State-Heat-Equation-No-Time-Dependence-NonlinearProblem) is described as a nonlinear problem, but it's fully linear. Why is this solved using `NonlinearSolve.solve`?

Conversely, the [Steady state of SIS](https://docs.sciml.ai/MethodOfLines/stable/tutorials/sispde/#Steady-state-of-SIS-(suspected-infected-suspected)-reaction-diffusion-model) problem is nonlinear, with factors like `S(t, x) * I(t, x) / (S(t, x) + I(t, x))`. Why does this one not use `NonlinearSolve`?

**Comment by xtalax** [comment]
Nonlinear refers to the type of systems of equations that are used to solve in each case. Steady state problems are nonlinear root finding problems, not ODEs hence they are solved with `NonlinearSolve`. Problems with time are typically lowered to ODEs, hence they use `OrdinaryDiffEq`
