### ISSUE TITLE
Docs for solving the heat equation: extract solution

### ISSUE THREAD

**Issue by ggebbie** [SciML/MethodOfLines.jl#349]
**Describe the bug 🐞**

When running the Solving the Heat Equation example in the docs, I got errors when trying to extract the solution.

**Expected behavior**

I expected to be able to run the provided code without error. I made some adjustments to extract the code (see snippet of code below).

**Minimal Reproducible Example 👇**

A snippet of the full code:
```julia
# Plot results and compare with exact solution
#discrete_x = sol[x] # didn't work
grid = get_discrete(pdesys, discretization)
discrete_x = grid[x]

#discrete_t = sol[t] # didn't work
discrete_t = sol.t # works

#solu = sol[u(t, x)] # didn't work
solu = sol.u[u(t, x)]
```

**Error & Stacktrace ⚠️**
Error related to `issymbollike`.

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
  [717857b8] DSP v0.7.9
  [31c24e10] Distributions v0.25.104
⌅ [5b8099bc] DomainSets v0.6.7
  [634d3b9d] DrWatson v2.13.0
  [09f84164] HypothesisTests v0.11.0
  [94925ecb] MethodOfLines v0.10.4
  [961ee093] ModelingToolkit v8.75.0
  [85f8d34a] NCDatasets v0.14.0
  [1dea7af3] OrdinaryDiffEq v6.67.0
  [f0f68f2c] PlotlyJS v0.18.11
  [91a5bcdd] Plots v1.39.0
  [1986cc42] Unitful v1.19.0
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated`

```

  - Output of `using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)`

```julia
 ERROR: UndefVarError: `PKGMODE_MANIFEST` not defined
```

  - Output of `versioninfo()`

```julia
Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
 
```

**Additional context**

**Comment by rjku** [comment]
Thank you for posting this issue.
I stumbled upon it.
—Riccardo

**Comment by cmhyett** [comment]
We've been actively working to remedy the `issymbollike` issue in PR #346.

**Comment by musoke** [comment]
Is this solved?  I see that the potential fix @cmhyett mentioned is merged.

**Comment by ggebbie** [comment]
This problem is solved when updating the package today. Great!

I can close the issue if that's ok with everyone. 

My environment that works contains the following:
```julia
  [717857b8] DSP v0.7.9
⌃ [31c24e10] Distributions v0.25.104
⌅ [5b8099bc] DomainSets v0.6.7
⌃ [634d3b9d] DrWatson v2.13.0
  [38e38edf] GLM v1.9.0
  [09f84164] HypothesisTests v0.11.0
  [b964fa9f] LaTeXStrings v1.3.1
  [94925ecb] MethodOfLines v0.10.6
  [961ee093] ModelingToolkit v8.75.0
⌃ [85f8d34a] NCDatasets v0.14.0
⌃ [1dea7af3] OrdinaryDiffEq v6.68.2
⌃ [f0f68f2c] PlotlyJS v0.18.11
⌃ [91a5bcdd] Plots v1.39.0
  [1986cc42] Unitful v1.19.0
```

**Comment by ggebbie** [comment]
closing
