### ISSUE TITLE
Latest version of MethodOfLines?

### ISSUE THREAD

**Issue by B-LIE** [SciML/MethodOfLines.jl#410]
**What is the latest version of MethodOfLines❓**

According to this GitHub page, the latest version is `v0.11.0`, released in April 2024.

However, when I do `pkg> add MethodOfLines`, `v0.11.2` seems to get installed. Furthermore, with `MethodOfLines` installed, this blocks `ModelingToolkit` from being updated from `v9.32.0` to `v9.34.0`.

**Comment by ChrisRackauckas** [comment]
Yes, TagBot just seems to have issues.

**Comment by DanielVandH** [comment]
Could the tags just be done manually?

**Comment by ChrisRackauckas** [comment]
![image](https://github.com/user-attachments/assets/bbd00175-53ea-4830-8795-f5efd5e44560)

**Comment by sathvikbhagavan** [comment]
Tagbot seems to be fixed now. We can close this?

**Comment by visr** [comment]
The last 7 patch releases have not been tagged

https://github.com/SciML/MethodOfLines.jl/issues/46#issuecomment-3948943603
