### ISSUE TITLE
Typos in the Brusselator PDE tutorial

### ISSUE THREAD

**Issue by dockerytong** [SciML/MethodOfLines.jl#55]
Missing comma and wrong parameter name while in discretization:

"discretization = MOLFiniteDifference([x=>dx, y=>dy], t, approx_order=order grid_type=center_align)"

 Which should be :

"discretization = MOLFiniteDifference([x=>dx, y=>dy], t, approx_order=order, grid_align=center_align)"

**Comment by xtalax** [comment]
Thank you! While you're here would you like any help solving a system?
