### ISSUE TITLE
MOLFiniteDifference return of the full PDE variables

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/MethodOfLines.jl#6]
Right now it returns each of the pieces of the solution, but it would be nice to get the observed variable handling working so that `sol[u]` returns the whole (shaped?) object for `u`. This requires upstream array symbolics and observed handling in ModelingToolkit.jl

**Comment by ChrisRackauckas** [comment]
This works IIRC? @xtalax

**Comment by xtalax** [comment]
Not the interpolations, @zoemcc did you get anywhere with the solution interfaces or should I spearhead this?
