### ISSUE TITLE
Error using discretize for Neumann and Robin boundary conditions, but not Dirichlet

### ISSUE THREAD

**Issue by thompsonmj** [SciML/MethodOfLines.jl#86]
Running examples from the heat equation [tutorial](http://methodoflines.sciml.ai/dev/tutorials/heat/) and my own problems, I get

`prob = discretize(pdesys,discretization)`

`ERROR: AssertionError: Number of offside points should not exceed the primary wind points`

using Neumann and Robin BCs, but it succeeds using Dirichlet.

(also a small note: the PDE system specification line in these docs should update from
`pdesys = PDESystem(eq,bcs,domains,[t,x],[u(t,x)])`
to
 `@named pdesys = PDESystem(eq,bcs,domains,[t,x],[u(t,x)]`)

**Comment by xtalax** [comment]
Compat issue with DiffEqOperators, hotfix incoming.

**Comment by xtalax** [comment]
Fixed in master, good catch

**Comment by xtalax** [comment]
Also possible to fix by doing `]dev DiffEqOperators`
