### ISSUE TITLE
Can `MethodOfLines` solve stochastic PDEs and PDEs with jumps? 

### ISSUE THREAD

**Issue by 00krishna** [SciML/MethodOfLines.jl#90]
Say, I was just wondering if `MethodOfLines` can solve stochastic PDEs and PDEs with jumps? I looked at the list of known limitations and it did say that these types of problems are excluded. Also, since MOL uses the DiffEq solvers--which support jumps and stochastic ODES, I thought that some of this might carry over to `MethodOfLines.` 

I looked through the test cases and did not seen any examples of a stochastic PDE. I imagine I could provide the noise model in the definitition of the SDEProblem.

Before I start all this, I figured I would just ask if these types of problems are supported yet. Thanks.

**Comment by ChrisRackauckas** [comment]
Not at this time.

**Comment by 00krishna** [comment]
Sounds good. I can close this issue for now then.
