### ISSUE TITLE
Feature request: support for integral terms

### ISSUE THREAD

**Issue by sdwfrost** [SciML/MethodOfLines.jl#94]
Help! All the PDE models I'm interested in integrate over one of the dimensions, and `NeuralPDE.jl` is too slow for many of them. As MOL is the standard way to discretize these models in the literature, would it be possible to add in support for integrals?

**Comment by ChrisRackauckas** [comment]
This library could evolve to solve integro-differential equations, but it does not at this time and it's probably not going to for at least a bit.

**Comment by xtalax** [comment]
Support for integrals from say 0..x are now merged, was this the type of limits you needed?

**Comment by sdwfrost** [comment]
The limits I need are integrals over the entire domain - here's a snippet:

```julia
@parameters t a
Dt = Differential(t)
Da = Differential(a)
Ia = Integral(a in DomainSets.ClosedInterval(0,52*75.0))
domains = [t ∈ (0,40.0), a ∈ (0,75*52)]
```

**Comment by xtalax** [comment]
alright, see you in MOL v0.7.6 :)
