### ISSUE TITLE
Possible issue with test case 00a in MOL 1d linear convection

### ISSUE THREAD

**Issue by 00krishna** [SciML/MethodOfLines.jl#95]
Hello @xtalax . I found a possible small error in test case 00a in the 1d linear convection tests.

Here is the link to the file and location. 

https://github.com/SciML/MethodOfLines.jl/blob/master/test/pde_systems/MOL_1D_Linear_Convection.jl#L66

The problem is that the test case is defined for "Dt(u(t,x)) ~ Dx(u(t,x))" on line 66.
BUT, line 74 of the file defines the equations as 
```
 eq  = Dt(u(t,x)) ~ -Dx(u(t,x))
```
So there seems to be an erroneus negative sign in front of the Dx term. I think this is probably just a copy and paste oversight from the first test case in the file 00, which does have a negative term. I just wanted to make sure that this was actually an error, or perhaps I just missed some code below where you removed that negative sign. 

@testset "Test 00a: Dt(u(t,x)) ~ Dx(u(t,x))" begin

**Comment by xtalax** [comment]
Good catch! I think that's just an error in the title, though I appreciate you taking the time to look at our source.

**Comment by 00krishna** [comment]
Okay cool. Yeah, I was not sure if you just wanted to test whether the code works in reverse :). Meaning that removing the negative sign just makes the convection roll from right to left. I gave it a try and it seemed to work just fine.
